name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen
    - name: run tests
      run: clang cmidi2_test.c -o cmidi2_test && ./cmidi2_test
